##encoding:utf-8
require 'fileutils'

NDK_ROOT="/home/ker/ndk"
COCOS_ROOT="/home/ker/cocos2dx"
CC="#{NDK_ROOT}/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++"
AR="#{NDK_ROOT}/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar"
LIB_NAME="ui"

src=[]
LOCAL_SRC_FILES = %w(
UIWidget
UILayout
UILayoutParameter
UILayoutManager
CocosGUI
UIHelper
UIListView
UIPageView
UIScrollView
UIButton
UICheckBox
UIImageView
UIText
UITextAtlas
UITextBMFont
UILoadingBar
UISlider
UITextField
UIRichText
CCProtectedNode
UIHBox
UIVBox
UIRelativeBox
UIVideoPlayerAndroid
UIDeprecated
)

FileUtils.mkdir_p("objs/#{LIB_NAME}") unless Dir.exists?("objs/#{LIB_NAME}")
LOCAL_SRC_FILES.each do |f|
	  		
	  		 sh="#{CC} -MMD -MP -MF objs/#{LIB_NAME}/#{f}.o.d"
	  		 sh<<" -gcc-toolchain #{NDK_ROOT}/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64"
	  		 sh<<" -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes"
	  		 sh<<" -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float" 
	  		 sh<<" -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing"
	  		 sh<<" -I#{COCOS_ROOT}/cocos/ui/.." 
	  		 sh<<" -I#{COCOS_ROOT}/cocos/ui/../../external"
	  		 sh<<" -I#{COCOS_ROOT}/cocos/ui/.." 
	  		 sh<<" -I#{COCOS_ROOT}/cocos/ui/../.." 
	  		 sh<<" -I#{COCOS_ROOT}/cocos/ui/../editor-support" 
	  		 sh<<" -I#{NDK_ROOT}/sources/cxx-stl/llvm-libc++/libcxx/include"
	  		 sh<<" -I#{NDK_ROOT}/sources/cxx-stl/llvm-libc++/../gabi++/include" 
	  		 sh<<" -I#{NDK_ROOT}/sources/cxx-stl/llvm-libc++/../../android/support/include" 
	  		 sh<<" -I#{COCOS_ROOT}/cocos/." 
	  		 sh<<" -I#{COCOS_ROOT}/cocos/./."
	  		 sh<<" -I#{COCOS_ROOT}/cocos/./platform/android"
	  		 sh<<" -I#{COCOS_ROOT}/cocos/./../external/tinyxml2"
	  		 sh<<" -I#{COCOS_ROOT}/cocos/./../external/unzip"
	  		 sh<<" -I#{COCOS_ROOT}/cocos/./../external/chipmunk/include/chipmunk"
	  		 sh<<" -I#{COCOS_ROOT}/cocos/./../external/xxhash"
	  		 sh<<" -I#{COCOS_ROOT}/cocos/./../external/nslog"
	  		 sh<<" -I#{COCOS_ROOT}/extensions/.."
	  		 sh<<" -I#{COCOS_ROOT}/extensions/GUI/CCControlExtension"
	  		 sh<<" -I#{COCOS_ROOT}/extensions/GUI/CCScrollView"
	  		 sh<<" -I#{COCOS_ROOT}/external/freetype2/prebuilt/android/../../include/android"
	  		 sh<<" -I#{COCOS_ROOT}/external/freetype2/prebuilt/android/../../include/android/freetype2"
	  		 sh<<" -I#{COCOS_ROOT}/external/chipmunk/include/chipmunk"
	  		 sh<<" -I#{COCOS_ROOT}/cocos/platform/android"
	  		 sh<<" -I#{COCOS_ROOT}/cocos/audio/android/../include"
	  		 sh<<" -I#{COCOS_ROOT}/external/curl/prebuilt/android/../../include/android"
	  		 sh<<" -I#{COCOS_ROOT}/external/Box2D/.."
	  		 sh<<" -I#{COCOS_ROOT}/external/websockets/prebuilt/android/../../include/android"
	  		 sh<<" -I#{COCOS_ROOT}/external/png/prebuilt/android/../../include/android"
	  		 sh<<" -I#{COCOS_ROOT}/external/jpeg/prebuilt/android/../../include/android"
	  		 sh<<" -I#{COCOS_ROOT}/external/tiff/prebuilt/android/../../include/android"
	  		 sh<<" -I#{COCOS_ROOT}/external/webp/prebuilt/android/../../include/android"
	  		 sh<<" -I#{NDK_ROOT}/sources/android/cpufeatures"
	  		 sh<<" -I#{COCOS_ROOT}/cocos/ui "
	  		 sh<<" -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security"
	  		 sh<<" -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1"
	  		 sh<<" -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -fsigned-char -DNDEBUG " 
	  		 sh<<" -I#{NDK_ROOT}/platforms/android-14/arch-arm/usr/include"
	  		 sh<<" -c #{COCOS_ROOT}/cocos/ui/#{f}.cpp"
	  		 sh<<" -o objs/#{LIB_NAME}/#{f}.o"
	  
	  		 puts sh
	  	   system sh
end	

FileUtils.mkdir_p("lib") unless Dir.exists?("lib")

sh="#{AR} crsD lib/lib#{LIB_NAME}.a"

src.each do |f|
	  sh<<" ./objs/#{LIB_NAME}/#{f}.o"
end
puts sh
system sh


=begin
[armeabi] Compile++ thumb: cocos_ui_static <= UIWidget.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ 
-MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIWidget.o.d 
-gcc-toolchain #{NDK_ROOT}/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 
-fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes 
-target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float 
-fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing 
-I#{COCOS_ROOT}/cocos/ui/.. 
-I#{COCOS_ROOT}/cocos/ui/../../external 
-I#{COCOS_ROOT}/cocos/ui/.. 
-I#{COCOS_ROOT}/cocos/ui/../.. 
-I#{COCOS_ROOT}/cocos/ui/../editor-support 
-I#{NDK_ROOT}/sources/cxx-stl/llvm-libc++/libcxx/include 
-I#{NDK_ROOT}/sources/cxx-stl/llvm-libc++/../gabi++/include 
-I#{NDK_ROOT}/sources/cxx-stl/llvm-libc++/../../android/support/include 
-I#{COCOS_ROOT}/cocos/. 
-I#{COCOS_ROOT}/cocos/./.
-I#{COCOS_ROOT}/cocos/./platform/android
-I#{COCOS_ROOT}/cocos/./../external/tinyxml2
-I#{COCOS_ROOT}/cocos/./../external/unzip
-I#{COCOS_ROOT}/cocos/./../external/chipmunk/include/chipmunk
-I#{COCOS_ROOT}/cocos/./../external/xxhash
-I#{COCOS_ROOT}/cocos/./../external/nslog
-I#{COCOS_ROOT}/extensions/..
-I#{COCOS_ROOT}/extensions/GUI/CCControlExtension
-I#{COCOS_ROOT}/extensions/GUI/CCScrollView
-I#{COCOS_ROOT}/external/freetype2/prebuilt/android/../../include/android
-I#{COCOS_ROOT}/external/freetype2/prebuilt/android/../../include/android/freetype2
-I#{COCOS_ROOT}/external/chipmunk/include/chipmunk
-I#{COCOS_ROOT}/cocos/platform/android
-I#{COCOS_ROOT}/cocos/audio/android/../include
-I#{COCOS_ROOT}/external/curl/prebuilt/android/../../include/android
-I#{COCOS_ROOT}/external/Box2D/..
-I#{COCOS_ROOT}/external/websockets/prebuilt/android/../../include/android
-I#{COCOS_ROOT}/external/png/prebuilt/android/../../include/android
-I#{COCOS_ROOT}/external/jpeg/prebuilt/android/../../include/android
-I#{COCOS_ROOT}/external/tiff/prebuilt/android/../../include/android
-I#{COCOS_ROOT}/external/webp/prebuilt/android/../../include/android
-I#{NDK_ROOT}/sources/android/cpufeatures
-I#{COCOS_ROOT}/cocos/ui 
-DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security
-std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1
-fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -fsigned-char -DNDEBUG  
-I#{NDK_ROOT}/platforms/android-14/arch-arm/usr/include
-c  /home/ker/cocos2dx/cocos/ui/UIWidget.cpp
-o ./obj/local/armeabi/objs/cocos_ui_static/UIWidget.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UILayout.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UILayout.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UILayout.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UILayout.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UILayoutParameter.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UILayoutParameter.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UILayoutParameter.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UILayoutParameter.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UILayoutManager.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UILayoutManager.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UILayoutManager.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UILayoutManager.o 
[armeabi] Compile++ thumb: cocos_ui_static <= CocosGUI.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/CocosGUI.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/CocosGUI.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/CocosGUI.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIHelper.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIHelper.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIHelper.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIHelper.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIListView.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIListView.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIListView.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIListView.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIPageView.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIPageView.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIPageView.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIPageView.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIScrollView.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIScrollView.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIScrollView.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIScrollView.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIButton.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIButton.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIButton.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIButton.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UICheckBox.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UICheckBox.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UICheckBox.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UICheckBox.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIImageView.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIImageView.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIImageView.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIImageView.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIText.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIText.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIText.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIText.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UITextAtlas.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UITextAtlas.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UITextAtlas.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UITextAtlas.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UITextBMFont.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UITextBMFont.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UITextBMFont.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UITextBMFont.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UILoadingBar.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UILoadingBar.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UILoadingBar.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UILoadingBar.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UISlider.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UISlider.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UISlider.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UISlider.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UITextField.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UITextField.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UITextField.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UITextField.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIRichText.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIRichText.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIRichText.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIRichText.o 
[armeabi] Compile++ thumb: cocos_ui_static <= CCProtectedNode.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/CCProtectedNode.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/CCProtectedNode.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/CCProtectedNode.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIHBox.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIHBox.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIHBox.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIHBox.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIVBox.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIVBox.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIVBox.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIVBox.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIRelativeBox.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIRelativeBox.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIRelativeBox.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIRelativeBox.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIVideoPlayerAndroid.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIVideoPlayerAndroid.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIVideoPlayerAndroid.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIVideoPlayerAndroid.o 
[armeabi] Compile++ thumb: cocos_ui_static <= UIDeprecated.cpp
/home/ker/ndk/toolchains/llvm-3.4/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/armeabi/objs/cocos_ui_static/UIDeprecated.o.d -gcc-toolchain /home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -target armv5te-none-linux-androideabi -march=armv5te -mtune=xscale -msoft-float -fno-exceptions -fno-rtti -mthumb -Os -g -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../../external -I/home/ker/cocos2dx/cocos/ui/.. -I/home/ker/cocos2dx/cocos/ui/../.. -I/home/ker/cocos2dx/cocos/ui/../editor-support -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/libcxx/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../gabi++/include -I/home/ker/ndk/sources/cxx-stl/llvm-libc++/../../android/support/include -I/home/ker/cocos2dx/cocos/. -I/home/ker/cocos2dx/cocos/./. -I/home/ker/cocos2dx/cocos/./platform/android -I/home/ker/cocos2dx/cocos/./../external/tinyxml2 -I/home/ker/cocos2dx/cocos/./../external/unzip -I/home/ker/cocos2dx/cocos/./../external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/./../external/xxhash -I/home/ker/cocos2dx/cocos/./../external/nslog -I/home/ker/cocos2dx/extensions/.. -I/home/ker/cocos2dx/extensions/GUI/CCControlExtension -I/home/ker/cocos2dx/extensions/GUI/CCScrollView -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 -Ijni/../../cocos2d/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/cocos/platform/android -I/home/ker/cocos2dx/cocos/audio/android/../include -Ijni/../../cocos2d/external/curl/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/Box2D/.. -Ijni/../../cocos2d/external/websockets/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/png/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/jpeg/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/tiff/prebuilt/android/../../include/android -Ijni/../../cocos2d/external/webp/prebuilt/android/../../include/android -I/home/ker/ndk/sources/android/cpufeatures -I/home/ker/cocos2dx/cocos/ui -DANDROID -DUSE_FILE32API -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -Wno-deprecated-declarations -Wno-extern-c-compat -D__STDC_LIMIT_MACROS=1 -fexceptions   -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DNDEBUG  -I/home/ker/ndk/platforms/android-14/arch-arm/usr/include -c  /home/ker/cocos2dx/cocos/ui/UIDeprecated.cpp -o ./obj/local/armeabi/objs/cocos_ui_static/UIDeprecated.o 
[armeabi] StaticLibrary  : libui.a
rm -f obj/local/armeabi/libui.a
/home/ker/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar 
crsD ./obj/local/armeabi/libui.a 
./obj/local/armeabi/objs/cocos_ui_static/UIWidget.o 
./obj/local/armeabi/objs/cocos_ui_static/UILayout.o 
./obj/local/armeabi/objs/cocos_ui_static/UILayoutParameter.o 
./obj/local/armeabi/objs/cocos_ui_static/UILayoutManager.o 
./obj/local/armeabi/objs/cocos_ui_static/CocosGUI.o 
./obj/local/armeabi/objs/cocos_ui_static/UIHelper.o 
./obj/local/armeabi/objs/cocos_ui_static/UIListView.o 
./obj/local/armeabi/objs/cocos_ui_static/UIPageView.o 
./obj/local/armeabi/objs/cocos_ui_static/UIScrollView.o 
./obj/local/armeabi/objs/cocos_ui_static/UIButton.o 
./obj/local/armeabi/objs/cocos_ui_static/UICheckBox.o 
./obj/local/armeabi/objs/cocos_ui_static/UIImageView.o 
./obj/local/armeabi/objs/cocos_ui_static/UIText.o 
./obj/local/armeabi/objs/cocos_ui_static/UITextAtlas.o 
./obj/local/armeabi/objs/cocos_ui_static/UITextBMFont.o 
./obj/local/armeabi/objs/cocos_ui_static/UILoadingBar.o 
./obj/local/armeabi/objs/cocos_ui_static/UISlider.o 
./obj/local/armeabi/objs/cocos_ui_static/UITextField.o 
./obj/local/armeabi/objs/cocos_ui_static/UIRichText.o 
./obj/local/armeabi/objs/cocos_ui_static/CCProtectedNode.o 
./obj/local/armeabi/objs/cocos_ui_static/UIHBox.o 
./obj/local/armeabi/objs/cocos_ui_static/UIVBox.o 
./obj/local/armeabi/objs/cocos_ui_static/UIRelativeBox.o 
./obj/local/armeabi/objs/cocos_ui_static/UIVideoPlayerAndroid.o 
./obj/local/armeabi/objs/cocos_ui_static/UIDeprecated.o
=end