##encoding:utf-8

require 'fileutils'
COCOS_ROOT="/home/ker/cocos2dx"
CC="c++"
AR="ar"
LIB_NAME="box2d"


LOCAL_SRC_FILES = %w(
Collision/b2BroadPhase.cpp
Collision/b2CollideCircle.cpp
Collision/b2CollideEdge.cpp
Collision/b2CollidePolygon.cpp
Collision/b2Collision.cpp
Collision/b2Distance.cpp
Collision/b2DynamicTree.cpp
Collision/b2TimeOfImpact.cpp
Collision/Shapes/b2ChainShape.cpp
Collision/Shapes/b2CircleShape.cpp
Collision/Shapes/b2EdgeShape.cpp
Collision/Shapes/b2PolygonShape.cpp
Common/b2BlockAllocator.cpp
Common/b2Draw.cpp
Common/b2Math.cpp
Common/b2Settings.cpp
Common/b2StackAllocator.cpp
Common/b2Timer.cpp
Dynamics/b2Body.cpp
Dynamics/b2ContactManager.cpp
Dynamics/b2Fixture.cpp
Dynamics/b2Island.cpp
Dynamics/b2World.cpp
Dynamics/b2WorldCallbacks.cpp
Dynamics/Contacts/b2ChainAndCircleContact.cpp
Dynamics/Contacts/b2ChainAndPolygonContact.cpp
Dynamics/Contacts/b2CircleContact.cpp
Dynamics/Contacts/b2Contact.cpp
Dynamics/Contacts/b2ContactSolver.cpp
Dynamics/Contacts/b2EdgeAndCircleContact.cpp
Dynamics/Contacts/b2EdgeAndPolygonContact.cpp
Dynamics/Contacts/b2PolygonAndCircleContact.cpp
Dynamics/Contacts/b2PolygonContact.cpp
Dynamics/Joints/b2DistanceJoint.cpp
Dynamics/Joints/b2FrictionJoint.cpp
Dynamics/Joints/b2GearJoint.cpp
Dynamics/Joints/b2Joint.cpp
Dynamics/Joints/b2MotorJoint.cpp
Dynamics/Joints/b2MouseJoint.cpp
Dynamics/Joints/b2PrismaticJoint.cpp
Dynamics/Joints/b2PulleyJoint.cpp
Dynamics/Joints/b2RevoluteJoint.cpp
Dynamics/Joints/b2RopeJoint.cpp
Dynamics/Joints/b2WeldJoint.cpp
Dynamics/Joints/b2WheelJoint.cpp
Rope/b2Rope.cpp)



FileUtils.mkdir_p("objs/#{LIB_NAME}") unless Dir.exists?("objs/#{LIB_NAME}")
LOCAL_SRC_FILES.each do |f|
	if f.include?('/')
	  i=f.rindex('/')
	  FileUtils.mkdir_p "objs/#{LIB_NAME}/#{f[0,i]}" unless Dir.exists? "objs/#{LIB_NAME}/#{f[0,i]}"
  end
   sh="#{CC} -DCC_ENABLE_CHIPMUNK_INTEGRATION=1"
		sh<<" -DLINUX"
		sh<<" -std=c++11"
		sh<<" -g"
		sh<<" -Wall"
		sh<<" -DCOCOS2D_DEBUG=1"
		sh<<" -fPIC"
		sh<<" -I#{COCOS_ROOT}"
		sh<<" -I#{COCOS_ROOT}/cocos"
		sh<<" -I#{COCOS_ROOT}/cocos/platform/desktop"
		sh<<" -I#{COCOS_ROOT}/cocos/platform/linux"
		sh<<" -I#{COCOS_ROOT}/cocos/audio/include"
		sh<<" -I#{COCOS_ROOT}/cocos/editor-support"
		sh<<" -I#{COCOS_ROOT}/cocos/scripting/lua-bindings/auto"
		sh<<" -I#{COCOS_ROOT}/cocos/scripting/lua-bindings/manual"
		sh<<" -I#{COCOS_ROOT}/extensions"
		sh<<" -I#{COCOS_ROOT}/external"
		sh<<" -I#{COCOS_ROOT}/external/tinyxml2"
		sh<<" -I#{COCOS_ROOT}/external/unzip"
		sh<<" -I#{COCOS_ROOT}/external/edtaa3func"
		sh<<" -I#{COCOS_ROOT}/external/chipmunk/include/chipmunk"
		sh<<" -I#{COCOS_ROOT}/external/jpeg/include/linux"
		sh<<" -I#{COCOS_ROOT}/external/png/include/linux"
		sh<<" -I#{COCOS_ROOT}/external/tiff/include/linux"
		sh<<" -I#{COCOS_ROOT}/external/webp/include/linux"
		sh<<" -I#{COCOS_ROOT}/external/glfw3/include/linux"
		sh<<" -I#{COCOS_ROOT}/external/freetype2/include/linux"
		sh<<" -I#{COCOS_ROOT}/external/websockets/include/linux"
		sh<<" -I#{COCOS_ROOT}/external/xxhash"
		sh<<" -I#{COCOS_ROOT}/external/xxtea"
		sh<<" -I/usr/include/GLFW"
		sh<<" -I/usr/local/include/GLFW"
		sh<<" -I#{COCOS_ROOT}/external/linux-specific/fmod/include/64-bit"
		sh<<" -I#{COCOS_ROOT}/external/Box2D/..   "
		sh<<" -o objs/#{LIB_NAME}/#{f}.o "
		sh<<" -c #{COCOS_ROOT}/external/Box2D/#{f}"
   puts sh
	 system sh
end	

FileUtils.mkdir_p("lib") unless Dir.exists?("lib")
sh="#{AR} crsD lib/lib#{LIB_NAME}.a"
LOCAL_SRC_FILES.each do |f|
	  sh<<" ./objs/#{LIB_NAME}/#{f}.o"
end
puts sh
system sh


=begin
Scanning dependencies of target box2d
make[2]:正在离开目录 `/home/ker/cocos2dx/ubuntu'
make -f external/Box2D/CMakeFiles/box2d.dir/build.make external/Box2D/CMakeFiles/box2d.dir/build
make[2]: 正在进入目录 `/home/ker/cocos2dx/ubuntu'
/usr/bin/cmake
-E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  4%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Collision/Shapes/b2ChainShape.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++  
-DCC_ENABLE_CHIPMUNK_INTEGRATION=1
-DLINUX
-std=c++11
-g
-Wall
-DCOCOS2D_DEBUG=1
-fPIC
-I/home/ker/cocos2dx
-I/home/ker/cocos2dx/cocos
-I/home/ker/cocos2dx/cocos/platform/desktop
-I/home/ker/cocos2dx/cocos/platform/linux
-I/home/ker/cocos2dx/cocos/audio/include
-I/home/ker/cocos2dx/cocos/editor-support
-I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto
-I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual
-I/home/ker/cocos2dx/extensions
-I/home/ker/cocos2dx/external
-I/home/ker/cocos2dx/external/tinyxml2
-I/home/ker/cocos2dx/external/unzip
-I/home/ker/cocos2dx/external/edtaa3func
-I/home/ker/cocos2dx/external/chipmunk/include/chipmunk
-I/home/ker/cocos2dx/external/jpeg/include/linux
-I/home/ker/cocos2dx/external/png/include/linux
-I/home/ker/cocos2dx/external/tiff/include/linux
-I/home/ker/cocos2dx/external/webp/include/linux
-I/home/ker/cocos2dx/external/glfw3/include/linux
-I/home/ker/cocos2dx/external/freetype2/include/linux
-I/home/ker/cocos2dx/external/websockets/include/linux
-I/home/ker/cocos2dx/external/xxhash
-I/home/ker/cocos2dx/external/xxtea
-I/usr/include/GLFW
-I/usr/local/include/GLFW
-I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit
-I/home/ker/cocos2dx/external/Box2D/..   
-o CMakeFiles/box2d.dir/Collision/Shapes/b2ChainShape.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Collision/Shapes/b2ChainShape.cpp
/usr/bin/cmake
-E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  4%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Collision/Shapes/b2CircleShape.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++  
-DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Collision/Shapes/b2CircleShape.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Collision/Shapes/b2CircleShape.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  4%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Collision/Shapes/b2EdgeShape.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Collision/Shapes/b2EdgeShape.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Collision/Shapes/b2EdgeShape.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  4%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Collision/Shapes/b2PolygonShape.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Collision/Shapes/b2PolygonShape.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Collision/Shapes/b2PolygonShape.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 1
[  5%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Collision/b2BroadPhase.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Collision/b2BroadPhase.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Collision/b2BroadPhase.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  5%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Collision/b2CollideCircle.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Collision/b2CollideCircle.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Collision/b2CollideCircle.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  5%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Collision/b2CollideEdge.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Collision/b2CollideEdge.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Collision/b2CollideEdge.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  5%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Collision/b2CollidePolygon.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Collision/b2CollidePolygon.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Collision/b2CollidePolygon.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  5%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Collision/b2Collision.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Collision/b2Collision.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Collision/b2Collision.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  5%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Collision/b2Distance.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Collision/b2Distance.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Collision/b2Distance.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 2
[  6%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Collision/b2DynamicTree.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Collision/b2DynamicTree.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Collision/b2DynamicTree.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  6%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Collision/b2TimeOfImpact.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Collision/b2TimeOfImpact.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Collision/b2TimeOfImpact.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  6%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Common/b2BlockAllocator.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Common/b2BlockAllocator.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Common/b2BlockAllocator.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  6%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Common/b2Draw.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Common/b2Draw.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Common/b2Draw.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  6%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Common/b2Math.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Common/b2Math.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Common/b2Math.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  6%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Common/b2Settings.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Common/b2Settings.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Common/b2Settings.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  6%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Common/b2StackAllocator.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Common/b2StackAllocator.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Common/b2StackAllocator.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 3
[  7%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Common/b2Timer.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Common/b2Timer.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Common/b2Timer.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  7%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Contacts/b2ChainAndCircleContact.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Contacts/b2ChainAndCircleContact.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  7%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Contacts/b2ChainAndPolygonContact.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Contacts/b2ChainAndPolygonContact.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  7%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Contacts/b2CircleContact.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Contacts/b2CircleContact.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Contacts/b2CircleContact.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  7%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Contacts/b2Contact.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Contacts/b2Contact.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Contacts/b2Contact.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  7%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Contacts/b2ContactSolver.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Contacts/b2ContactSolver.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Contacts/b2ContactSolver.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 4
[  8%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Contacts/b2EdgeAndCircleContact.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Contacts/b2EdgeAndCircleContact.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  8%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Contacts/b2EdgeAndPolygonContact.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Contacts/b2EdgeAndPolygonContact.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  8%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Contacts/b2PolygonAndCircleContact.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Contacts/b2PolygonAndCircleContact.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  8%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Contacts/b2PolygonContact.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Contacts/b2PolygonContact.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Contacts/b2PolygonContact.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  8%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Joints/b2DistanceJoint.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Joints/b2DistanceJoint.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Joints/b2DistanceJoint.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  8%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Joints/b2FrictionJoint.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Joints/b2FrictionJoint.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Joints/b2FrictionJoint.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  8%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Joints/b2GearJoint.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Joints/b2GearJoint.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Joints/b2GearJoint.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 5
[  9%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Joints/b2Joint.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Joints/b2Joint.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Joints/b2Joint.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  9%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Joints/b2MouseJoint.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Joints/b2MouseJoint.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Joints/b2MouseJoint.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  9%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Joints/b2MotorJoint.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Joints/b2MotorJoint.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Joints/b2MotorJoint.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  9%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Joints/b2PrismaticJoint.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Joints/b2PrismaticJoint.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Joints/b2PrismaticJoint.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  9%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Joints/b2PulleyJoint.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Joints/b2PulleyJoint.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Joints/b2PulleyJoint.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[  9%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Joints/b2RevoluteJoint.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Joints/b2RevoluteJoint.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Joints/b2RevoluteJoint.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 6
[ 10%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Joints/b2RopeJoint.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Joints/b2RopeJoint.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Joints/b2RopeJoint.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[ 10%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Joints/b2WeldJoint.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Joints/b2WeldJoint.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Joints/b2WeldJoint.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[ 10%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/Joints/b2WheelJoint.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/Joints/b2WheelJoint.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/Joints/b2WheelJoint.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[ 10%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/b2Body.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/b2Body.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/b2Body.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[ 10%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/b2ContactManager.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/b2ContactManager.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/b2ContactManager.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[ 10%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/b2Fixture.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/b2Fixture.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/b2Fixture.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[ 10%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/b2Island.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/b2Island.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/b2Island.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 7
[ 11%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/b2World.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/b2World.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/b2World.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[ 11%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Dynamics/b2WorldCallbacks.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Dynamics/b2WorldCallbacks.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Dynamics/b2WorldCallbacks.cpp
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[ 11%] Building CXX object external/Box2D/CMakeFiles/box2d.dir/Rope/b2Rope.cpp.o
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/c++   -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -DLINUX -std=c++11 -g -Wall -DCOCOS2D_DEBUG=1 -fPIC -I/home/ker/cocos2dx -I/home/ker/cocos2dx/cocos -I/home/ker/cocos2dx/cocos/platform/desktop -I/home/ker/cocos2dx/cocos/platform/linux -I/home/ker/cocos2dx/cocos/audio/include -I/home/ker/cocos2dx/cocos/editor-support -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/auto -I/home/ker/cocos2dx/cocos/scripting/lua-bindings/manual -I/home/ker/cocos2dx/extensions -I/home/ker/cocos2dx/external -I/home/ker/cocos2dx/external/tinyxml2 -I/home/ker/cocos2dx/external/unzip -I/home/ker/cocos2dx/external/edtaa3func -I/home/ker/cocos2dx/external/chipmunk/include/chipmunk -I/home/ker/cocos2dx/external/jpeg/include/linux -I/home/ker/cocos2dx/external/png/include/linux -I/home/ker/cocos2dx/external/tiff/include/linux -I/home/ker/cocos2dx/external/webp/include/linux -I/home/ker/cocos2dx/external/glfw3/include/linux -I/home/ker/cocos2dx/external/freetype2/include/linux -I/home/ker/cocos2dx/external/websockets/include/linux -I/home/ker/cocos2dx/external/xxhash -I/home/ker/cocos2dx/external/xxtea -I/usr/include/GLFW -I/usr/local/include/GLFW -I/home/ker/cocos2dx/external/linux-specific/fmod/include/64-bit -I/home/ker/cocos2dx/external/Box2D/..    -o CMakeFiles/box2d.dir/Rope/b2Rope.cpp.o 
-c /home/ker/cocos2dx/external/Box2D/Rope/b2Rope.cpp
Linking CXX static library ../../lib/libbox2d.a
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/cmake -P CMakeFiles/box2d.dir/cmake_clean_target.cmake
cd /home/ker/cocos2dx/ubuntu/external/Box2D && /usr/bin/cmake -E cmake_link_script CMakeFiles/box2d.dir/link.txt --verbose=1
/usr/bin/ar cr ../../lib/libbox2d.a  CMakeFiles/box2d.dir/Collision/Shapes/b2ChainShape.cpp.o CMakeFiles/box2d.dir/Collision/Shapes/b2CircleShape.cpp.o CMakeFiles/box2d.dir/Collision/Shapes/b2EdgeShape.cpp.o CMakeFiles/box2d.dir/Collision/Shapes/b2PolygonShape.cpp.o CMakeFiles/box2d.dir/Collision/b2BroadPhase.cpp.o CMakeFiles/box2d.dir/Collision/b2CollideCircle.cpp.o CMakeFiles/box2d.dir/Collision/b2CollideEdge.cpp.o CMakeFiles/box2d.dir/Collision/b2CollidePolygon.cpp.o CMakeFiles/box2d.dir/Collision/b2Collision.cpp.o CMakeFiles/box2d.dir/Collision/b2Distance.cpp.o CMakeFiles/box2d.dir/Collision/b2DynamicTree.cpp.o CMakeFiles/box2d.dir/Collision/b2TimeOfImpact.cpp.o CMakeFiles/box2d.dir/Common/b2BlockAllocator.cpp.o CMakeFiles/box2d.dir/Common/b2Draw.cpp.o CMakeFiles/box2d.dir/Common/b2Math.cpp.o CMakeFiles/box2d.dir/Common/b2Settings.cpp.o CMakeFiles/box2d.dir/Common/b2StackAllocator.cpp.o CMakeFiles/box2d.dir/Common/b2Timer.cpp.o CMakeFiles/box2d.dir/Dynamics/Contacts/b2ChainAndCircleContact.cpp.o CMakeFiles/box2d.dir/Dynamics/Contacts/b2ChainAndPolygonContact.cpp.o CMakeFiles/box2d.dir/Dynamics/Contacts/b2CircleContact.cpp.o CMakeFiles/box2d.dir/Dynamics/Contacts/b2Contact.cpp.o CMakeFiles/box2d.dir/Dynamics/Contacts/b2ContactSolver.cpp.o CMakeFiles/box2d.dir/Dynamics/Contacts/b2EdgeAndCircleContact.cpp.o CMakeFiles/box2d.dir/Dynamics/Contacts/b2EdgeAndPolygonContact.cpp.o CMakeFiles/box2d.dir/Dynamics/Contacts/b2PolygonAndCircleContact.cpp.o CMakeFiles/box2d.dir/Dynamics/Contacts/b2PolygonContact.cpp.o CMakeFiles/box2d.dir/Dynamics/Joints/b2DistanceJoint.cpp.o CMakeFiles/box2d.dir/Dynamics/Joints/b2FrictionJoint.cpp.o CMakeFiles/box2d.dir/Dynamics/Joints/b2GearJoint.cpp.o CMakeFiles/box2d.dir/Dynamics/Joints/b2Joint.cpp.o CMakeFiles/box2d.dir/Dynamics/Joints/b2MouseJoint.cpp.o CMakeFiles/box2d.dir/Dynamics/Joints/b2MotorJoint.cpp.o CMakeFiles/box2d.dir/Dynamics/Joints/b2PrismaticJoint.cpp.o CMakeFiles/box2d.dir/Dynamics/Joints/b2PulleyJoint.cpp.o CMakeFiles/box2d.dir/Dynamics/Joints/b2RevoluteJoint.cpp.o CMakeFiles/box2d.dir/Dynamics/Joints/b2RopeJoint.cpp.o CMakeFiles/box2d.dir/Dynamics/Joints/b2WeldJoint.cpp.o CMakeFiles/box2d.dir/Dynamics/Joints/b2WheelJoint.cpp.o CMakeFiles/box2d.dir/Dynamics/b2Body.cpp.o CMakeFiles/box2d.dir/Dynamics/b2ContactManager.cpp.o CMakeFiles/box2d.dir/Dynamics/b2Fixture.cpp.o CMakeFiles/box2d.dir/Dynamics/b2Island.cpp.o CMakeFiles/box2d.dir/Dynamics/b2World.cpp.o CMakeFiles/box2d.dir/Dynamics/b2WorldCallbacks.cpp.o CMakeFiles/box2d.dir/Rope/b2Rope.cpp.o
/usr/bin/ranlib ../../lib/libbox2d.a
make[2]:正在离开目录 `/home/ker/cocos2dx/ubuntu'
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles  1 2 3 4 5 6 7
[ 11%] Built target box2d

make[2]:正在离开目录 `/home/ker/cocos2dx/ubuntu'
/usr/bin/cmake -E cmake_progress_report /home/ker/cocos2dx/ubuntu/CMakeFiles 
[ 11%] Built target unzip
=end